"""Regression tests for HEVC MOV container handling.

A user's HEVC MOV was failing in the web worker with a generic
"Failed" status. These tests verify that:

1. ``detect_silence`` and ``extract_audio`` complete on a tiny HEVC MOV
   fixture generated by ffmpeg.
2. The job worker is importable without eagerly loading faster-whisper.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

FFMPEG = shutil.which("ffmpeg")

pytestmark = pytest.mark.skipif(FFMPEG is None, reason="ffmpeg not available")


@pytest.fixture(scope="module")
def hevc_mov(tmp_path_factory) -> Path:
    """Generate a tiny HEVC MOV with both video and audio streams."""
    out = tmp_path_factory.mktemp("hevc") / "sample.mov"
    cmd = [
        FFMPEG,
        "-y",
        "-f", "lavfi",
        "-i", "testsrc=duration=3:size=1280x720:rate=30",
        "-f", "lavfi",
        "-i", "sine=frequency=440:duration=3:sample_rate=16000",
        "-c:v", "hevc_videotoolbox",
        "-b:v", "2M",
        "-tag:v", "hvc1",
        "-c:a", "aac",
        "-shortest",
        str(out),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    if proc.returncode != 0 or not out.exists():
        pytest.skip(f"ffmpeg hevc generation failed: {proc.stderr[-300:]}")
    return out


def test_detect_silence_works_on_hevc_mov(hevc_mov: Path) -> None:
    from veauto.models import SilenceConfig
    from veauto.silence import detect_silence

    result = detect_silence(hevc_mov, SilenceConfig(noise_db=-30.0, min_silence=0.5))
    assert isinstance(result, list)
    for s in result:
        assert s.start >= 0
        assert s.end > s.start


def test_extract_audio_works_on_hevc_mov(hevc_mov: Path, tmp_path: Path) -> None:
    from veauto.audio import extract_audio

    out = tmp_path / "out.wav"
    result = extract_audio(hevc_mov, out)
    assert result.exists()
    assert result.stat().st_size > 0
    assert result.read_bytes()[:4] == b"RIFF"


def test_module_imports_cleanly() -> None:
    """Importing veauto.web.jobs should not eagerly load faster-whisper."""
    import importlib

    mod = importlib.import_module("veauto.web.jobs")
    assert hasattr(mod, "JobManager")
    assert hasattr(mod, "JobOptions")
